"""
employee model.

Auto-generated by crud-generate CLI tool.
"""
from typing import Optional
from uuid import UUID

from sqlalchemy import String, Integer, Boolean, Date, DateTime, Text, Float, Numeric, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel
from app.models.crm.mixins import PersonMixin, ContactMixin, EmployeeMixin


class Employee(BaseModel, PersonMixin, ContactMixin, EmployeeMixin):
    """
    Employee model.
    
Represents employee entities in the system.    """
    __tablename__ = "employees"
    
    
    # first_name
    first_name: Mapped[str] = mapped_column(
        String(255), nullable=False,
        doc="The first_name field"    )
    
    # last_name
    last_name: Mapped[str] = mapped_column(
        String(255), nullable=False,
        doc="The last_name field"    )
    
    # email
    email: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False,
        doc="The email field"    )
    
    def __repr__(self) -> str:
        """String representation."""
        return f"<Employee(id={self.id}, first_name='{self.first_name}', last_name='{self.last_name}')>"