"""Create employee table

Revision ID: 05766dd4de23
Revises: None
Create Date: 2025-10-22T08:36:22.549027

Auto-generated by crud-generate CLI tool.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05766dd4de23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    op.create_table(
        'employees',
        # Primary key
        sa.Column('id', sa.UUID(), nullable=False),
        
        # Custom fields
        sa.Column('first_name', sa.String(255), nullable=False),
        sa.Column('last_name', sa.String(255), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        
        # Timestamp fields
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        
        # Soft delete fields
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        
        # Audit fields
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('updated_by_id', sa.UUID(), nullable=True),
        
        # Primary key constraint
        sa.PrimaryKeyConstraint('id'),
        
        # Unique constraints
        sa.UniqueConstraint('email'),
    )
    
    # Create indexes
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.create_index('ix_employees_is_deleted', 'employees', ['is_deleted'], unique=False)


def downgrade() -> None:
    """Downgrade database schema."""
    # Drop indexes
    op.drop_index('ix_employees_is_deleted', table_name='employees')
    op.drop_index('ix_employees_id', table_name='employees')
    
    # Drop table
    op.drop_table('employees')