"""add_missing_employee_columns

Revision ID: ae6f9dd01ab4
Revises: 4ca30cba7f50
Create Date: 2025-10-23 15:41:01.690767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6f9dd01ab4'
down_revision = '4ca30cba7f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('address1', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('address2', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('employee_number', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('hire_date', sa.Date(), nullable=False))
    op.add_column('employees', sa.Column('position_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('manager_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_position_id'), 'employees', ['position_id'], unique=False)
    op.create_foreign_key(op.f('fk_employees_position_id_positions'), 'employees', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_positions_code_is_deleted'), table_name='positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_positions_code_is_deleted'), 'positions', ['code', 'is_deleted'], unique=True)
    op.drop_constraint(op.f('fk_employees_position_id_positions'), 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_position_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_column('employees', 'manager_id')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'position_id')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'employee_number')
    op.drop_column('employees', 'country')
    op.drop_column('employees', 'zip_code')
    op.drop_column('employees', 'state')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'address2')
    op.drop_column('employees', 'address1')
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###